### ISSUE TITLE
ICSS2 implementation questions

### ISSUE THREAD

**Issue by TrySound** [css-modules/icss#14]
1. How to deal with imported media queries? I got a bit of mess in [postcss-import](https://github.com/postcss/postcss-import) to resolve `and` and `or` operators. Should we even implement whole spec complexity.

```css
// imported.css
@media screen or (min-width: 2) { .foo {} }
.bar {}
// importer.css
@import "imported.css" (max-width: 3);
// becomes
@media screen and (max-width: 3) or (min-widh: 2) and (max-width: 3) { .foo {} }
@media (max-width: 3) { .bar {} }
```

2. Should imported identifiers be localized If `local-by-default` is enabled? Spec allows to specify exported tokens but `@import` syntax is too simple for that. So only :global improted identifiers make sense.

```css
// imported.css
.foo {}
// importer.css
@import 'imported.css';
.bar {}
// becomes
.foo--hash {}
.bar--hash {}
:export {
  bar: bar--hash;
}
```

Ref https://medium.com/@sokra/79583bd107d7

/cc @sokra @geelen @sullenor @michael-ciniawsky
