### ISSUE TITLE
Supporting global sections

### ISSUE THREAD

**Issue by joepie91** [css-modules/icss#16]
Right now, if we have a bunch of global classes, that are interpreted in a locals-by-default context, we need to do this:

```css
:global .classOne {
	background-color: black;
}

:global .classTwo {
	color: yellow;
}

/* This one is local */
.classThree {
	border: 1px solid yellow;
}
```

It would be nice if we could do something like this instead:

```css
:global {
	.classOne {
		background-color: black;
	}

	.classTwo {
		color: yellow;
	}
}

/* This one is local */
.classThree {
	border: 1px solid yellow;
}
```
